### PR TITLE
State callback functionality in Core

### LINKED ISSUE #27: Replace busy loops with M64Plus callbacks
Currently we're busy waiting for Mupen64Plus to start / stop. Under some circumstances this does not correctly work and the emulator (and frontend) crash. For example in Mupen64Plus::stop(): https://github.com/net64-mod/net64-coop/blob/8594cb2aa8c1c2968a52553b7a519edc48708fc0/src/core/emulator/m64plus.cpp#L474-L486

Instead we should set a StateCallback in CoreStartup to receive state updates reliably and non blocking. The following state changes can be caught using the callback: https://github.com/net64-mod/net64-coop/blob/8594cb2aa8c1c2968a52553b7a519edc48708fc0/externals/mupen64plus/m64p_types.h#L129-L141

More info in the [wiki](http://www.mupen64plus.org/wiki/index.php?title=Mupen64Plus_v2.0_Core_Front-End).

### PR DESCRIPTION
**Pull request by mrexodia**
closes #27

### CODE REVIEW

File: src/net64/emulator/m64plus.cpp [hunk 1]
```diff
@@ -25,61 +25,46 @@ bool failed(Mupen64Plus::Error err)
...
 }
 
 void Mupen64Plus::remove_plugin(M64PTypes::m64p_plugin_type type)
 {
-    assert(!running_);
+    std::lock_guard g(mutex_);
+    assert(!running());
 
-    plugins_[type] = {};
+    plugins_[type] = nullptr;
```
Comment (Henrik0x7F) [inline src/net64/emulator/m64plus.cpp]: I think plugins_[type].reset() would be more clear

File: src/net64/emulator/m64plus.cpp [hunk 2]
```diff
@@ -92,6 +77,9 @@ void Mupen64Plus::load_rom(void* rom_data, std::size_t n)
 
 void Mupen64Plus::unload_rom()
 {
+    std::lock_guard g(mutex_);
+    assert(rom_loaded_);
```
Comment (Henrik0x7F) [inline src/net64/emulator/m64plus.cpp:81]: You are not supposed to unload the ROM while the emulator is running. So an additional `state_ == State::STOPPED` check would be a good idea

File: src/net64/emulator/m64plus.cpp [hunk 3]
```diff
@@ -104,73 +92,126 @@ void Mupen64Plus::unload_rom()
...
+    state_ = State::Stopping;
+    mutex_.unlock();
 
-Mupen64Plus::Core& Mupen64Plus::core()
-{
-    return core_;
+    // Wait for the emulator to be stopped
+    while(state_ != State::Stopped)
+    {
+        core_.do_cmd(M64PTypes::M64CMD_STOP, 0, nullptr);
```
Comment (Henrik0x7F) [inline src/net64/emulator/m64plus.cpp:190]: Do you have any idea why this is needed? During the first call to stop in line 180 the emulator is already RUNNING and should correctly receive the stop command. Yet without the repeated stop calls it doesn't work.

File: src/net64/emulator/m64plus.hpp [hunk 4]
```diff
@@ -13,15 +13,15 @@
...
 #include "net64/emulator/emulator.hpp"
 #include "net64/emulator/shared_library.hpp"
 #include "net64/logging.hpp"
 
 
 namespace Net64::Emulator
 {
-
-struct Mupen64Plus;
+class Mupen64Plus;
```
Comment (Henrik0x7F) [inline src/net64/emulator/m64plus.hpp:24]: Why did you change it to class? I prefer struct since its default visibility better fits the layout of most objects (first public, then private).

File: src/net64/emulator/m64plus.hpp [hunk 5]
```diff
@@ -32,7 +32,7 @@ namespace M64PTypes
 namespace M64PlusHelper
 {
 
-struct Plugin;
+class Plugin;
```
Comment (Henrik0x7F) [inline src/net64/emulator/m64plus.hpp:35]: Same

File: src/net64/emulator/m64plus.hpp [hunk 6]
```diff
@@ -76,12 +76,20 @@ struct PluginInfo
 /**
  * Dynamically loaded Mupen64Plus core
  */
-struct Core
+class Core final
```
Comment (Henrik0x7F) [inline src/net64/emulator/m64plus.hpp:79]: Again, please revert it back to struct

File: src/net64/emulator/m64plus.hpp [hunk 7]
```diff
@@ -184,8 +193,28 @@ struct Core
 /**
  * Dynamically loaded Mupen64Plus plugin
  */
-struct Plugin
+class Plugin final
```
Comment (Henrik0x7F) [inline src/net64/emulator/m64plus.hpp:200]: Please use struct

File: src/net64/emulator/m64plus.hpp [hunk 8]
```diff
@@ -256,35 +262,31 @@ struct Plugin
 } // M64PlusHelper
 
 /**
- * Mupen64Plus instance
+ * Mupen64Plus instance. Only one instance of this class can be alive at a time.
  */
-struct Mupen64Plus final : IEmulator
+class Mupen64Plus final : IEmulator
```
Comment (Henrik0x7F) [inline src/net64/emulator/m64plus.hpp]: Here replacing struct with class actually causes an issue since you are now inheriting from IEmulator privately

File: src/net64/emulator/m64plus.cpp [hunk 9]
```diff
@@ -188,11 +229,30 @@ void Mupen64Plus::check_bounds(addr_t addr, usize_t size)
         logger()->error("Out of bounds memory access at address {:#x} (size: {:#x})", addr, size);
         throw std::system_error(errc);
     }
+}
+
+void Mupen64Plus::emulation_started() noexcept
```
Comment (Henrik0x7F) [inline src/net64/emulator/m64plus.cpp]: I think this should be a callback which can be set by whomever is managing Mupen64Plus. It's not really the responsibility of Mupen64Plus to load patches.

File: src/net64/emulator/m64plus.cpp [hunk 10]
```diff
@@ -104,73 +92,126 @@ void Mupen64Plus::unload_rom()
...
+    {
+        mutex_.unlock();
+        return;
+    }
+
+    state_ = State::Starting;
     core_.prepare_config_file();
     attach_plugins();
-    logger()->info("Started n64 emulation");
+    core_.set_state_callback([this](M64PTypes::m64p_core_param param_type, int new_value) noexcept
```
Comment (Henrik0x7F) [inline src/net64/emulator/m64plus.cpp:114]: It might also be a good idea to forward this callback to the manager of Mupen64Plus to keep track of Mupen64's state.

**Review by Henrik0x7F — CHANGES_REQUESTED** [review]
This looks very solid, thank you. Please fix the minor issues so I can merge it.

File: src/net64/emulator/m64plus.hpp (hunk 5 above)
Comment (mrexodia) [reply src/net64/emulator/m64plus.hpp:35]: `Plugin` is now private and friends with `Mupen64Plus` and since you used the default visibility of `struct` I'm using the default visibility of `class`

File: src/net64/emulator/m64plus.hpp (hunk 6 above)
Comment (mrexodia) [reply src/net64/emulator/m64plus.hpp:79]: `Core` is now private and friends with `Mupen64Plus` and since you used the default visibility of `struct` I'm using the default visibility of `class`

File: src/net64/emulator/m64plus.hpp (hunk 8 above)
Comment (mrexodia) [reply src/net64/emulator/m64plus.hpp]: That is definitely a bug

File: src/net64/emulator/m64plus.cpp (hunk 9 above)
Comment (mrexodia) [reply src/net64/emulator/m64plus.cpp]: Yeah I'll remove the comment, because it turned out to be not true.

File: src/net64/emulator/m64plus.cpp (hunk 10 above)
Comment (mrexodia) [reply src/net64/emulator/m64plus.cpp:114]: I disagree. The state machine is so complex that nobody but `Mupen64Plus` should be managing it.

File: src/net64/emulator/m64plus.cpp (hunk 3 above)
Comment (mrexodia) [reply src/net64/emulator/m64plus.cpp:190]: Stop is implemented like this:

```
void stop_device(struct device* dev)
{
    /* set stop flag so that r4300 execution will be stopped at next interrupt */
    *r4300_stop(&dev->r4300) = 1;
}
```

However during startup:

```
/* Startup message on the OSD */
    osd_new_message(OSD_MIDDLE_CENTER, "Mupen64Plus Started...");

    g_EmulatorRunning = 1;
    StateChanged(M64CORE_EMU_STATE, M64EMU_RUNNING); //here

    poweron_device(&g_dev);
    pif_bootrom_hle_execute(&g_dev.r4300);
    run_device(&g_dev);
```

We receive `M64EMU_RUNNING` before `poweron_device`, inside of which there is a memset on the whole `r4300` struct. Anyway, the answer is basically: because of a bug in mupen. I'll open a PR that fixes this in core, but for now this workaround has to stay.

Comment (mrexodia) [reply src/net64/emulator/m64plus.cpp:190]: I opened https://github.com/mupen64plus/mupen64plus-core/issues/681 so they will maybe fix it in core and also added `std::this_thread::yield()` in the loop to make it not so hot.

**Comment by mrexodia** [comment]
Alright, everything should be done now!

**Review by Henrik0x7F — APPROVED** [review]
